

        -- MySQL Script generated by MySQL Workbench
        -- Thu Jun 16 00:11:27 2022
        -- Model: New Model    Version: 1.0
        -- MySQL Workbench Forward Engineering

        SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
        SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
        SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

        -- -----------------------------------------------------
        -- Schema upact
        -- -----------------------------------------------------

        -- -----------------------------------------------------
        -- Schema upact
        -- -----------------------------------------------------
        CREATE SCHEMA IF NOT EXISTS `upact` DEFAULT CHARACTER SET utf8 ;
        USE `upact` ;

        -- -----------------------------------------------------
        -- Table `upact`.`state`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `upact`.`state` (
        `state_id` INT  UNSIGNED NOT NULL AUTO_INCREMENT ,
        `name` VARCHAR(45) NOT NULL,
        `abrv` VARCHAR(2) NOT NULL,
        PRIMARY KEY (`state_id`),
        UNIQUE INDEX `state_id_UNIQUE` (`state_id` ASC) VISIBLE,
        UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
        UNIQUE INDEX `abrv_UNIQUE` (`abrv` ASC) VISIBLE)
        ENGINE = InnoDB;


        -- -----------------------------------------------------
        -- Table `upact`.`identifier`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `upact`.`identifier` (
        `identifier_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
        `city` VARCHAR(45) NOT NULL,
        `street` VARCHAR(45) NOT NULL,
        `number` INT NULL,
        `venue` VARCHAR(45) NOT NULL,
        `name` VARCHAR(45) NOT NULL,
        `start_date` DATE NOT NULL,
        `end_date` DATE NOT NULL,
        `distance` INT NOT NULL,
        `price` FLOAT NOT NULL,
        `website` VARCHAR(80) NOT NULL,
        `type` VARCHAR(25) NULL,
        `state_id` INT UNSIGNED NOT NULL,
        PRIMARY KEY (`identifier_id`),
        INDEX `fk_identifier_state_idx` (`state_id` ASC) VISIBLE)
        ENGINE = InnoDB;


        SET SQL_MODE=@OLD_SQL_MODE;
        SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
        SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

